### PR TITLE
Update for package:test; onPrint->onMessage

### PR DESCRIPTION
**Pull request by davidmorgan**

### CODE REVIEW

**Comment by nex3** [comment]
What's the context for this pull request? My understanding was that `metatest` was no longer in use now that `scheduled_test` has been phased out.

**Comment by davidmorgan** [comment]
I'm getting the last few packages in google3 strong mode compliant.

I still see uses of scheduled_test from barback, dart_style, glob, shelf_proxy, shelf_static and watcher. So removing it (and hence metatest) doesn't look like an option.

**Comment by davidmorgan** [comment]
Friendly ping. Just a few packages left now :)

I can also apply this patch internally only if you prefer.

**Comment by nex3** [comment]
> I still see uses of scheduled_test from barback, dart_style, glob, shelf_proxy, shelf_static and watcher. So removing it (and hence metatest) doesn't look like an option.

Of these, I believe only `barback` and `watcher` still use `scheduled_test`—maybe the others still need to be pulled into Google3?

I'll see if I can get `watcher` moved to pure `test`, and I've filed https://github.com/dart-lang/barback/issues/93 for moving `barback`. In the meantime, I guess it makes sense to continue updating this... can you bump the version number and release?

**Comment by davidmorgan** [comment]
(Sorry for slow response). Sure. What should the version number be? I've never used a version scheme with '+' in there.

By release, do you mean pub and/or github? (Not sure if I have permission to release to pub?).

Thanks. (I'm no longer blocked on this, FWIW).

**Comment by nex3** [comment]
> (Sorry for slow response). Sure. What should the version number be? I've never used a version scheme with '+' in there.

0.2.2+4. See [this doc](https://docs.google.com/document/d/1kPhEF8rL53S45SpzboyddKW61EUn0KuKPYOvoPOazVE/edit) for details.

> By release, do you mean pub and/or github?

To pub. I've added you as an uploader.

**Comment by davidmorgan** [comment]
Done. Thanks.

**Pull request merged**
